In [1]:
from datasets import load_dataset
import re
from transformers import Qwen2VLForConditionalGenerationWithAudio, Qwen2VLConfig, Qwen2VLAudioConfig
from transformers import AutoConfig, AutoModelForCausalLM, AutoProcessor, Qwen2VLProcessor
from trl import SFTConfig, SFTTrainer
import wandb
import torch
from utils import format_data
from qwen_vl_utils import vision_process,fetch_audio
from huggingface_hub import HfApi

/home/ubuntu/audio/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
wandb.login(key="dd4083ce56792e5e46b3ad7f3f637b3439a6d164")
from huggingface_hub import login
login(token="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")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /home/ubuntu/.netrc
wandb: Currently logged in as: dmym (paypal) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [3]:
train_dataset = load_dataset("speechbrain/LargeScaleASR", data_files=["small/train-0000*","small/train-0001*"], num_proc=1)
test_dataset = load_dataset("speechbrain/LargeScaleASR", data_files=["test/test-00000*"], num_proc=1)

In [4]:
train_dataset = train_dataset["train"]
test_dataset = test_dataset["train"]
test_dataset = test_dataset.select(range(100)) # only 100 samples used for accelerated testing

In [5]:
train_dataset

Dataset({
    features: ['ID', 'duration', 'wav', 'spk_id', 'sex', 'text'],
    num_rows: 29820
})

In [6]:
print(len(train_dataset))
print(len(test_dataset))

29820
100

In [ ]:
import gc
import time
import torch
def clear_memory():
    # Delete variables if they exist in the current global scope
    if 'inputs' in globals(): del globals()['inputs']
    if 'model' in globals(): del globals()['model']
    if 'processor' in globals(): del globals()['processor']
    if 'trainer' in globals(): del globals()['trainer']
    if 'peft_model' in globals(): del globals()['peft_model']
    if 'bnb_config' in globals(): del globals()['bnb_config']
    time.sleep(2)

    # Garbage collection and clearing CUDA memory
    gc.collect()
    time.sleep(2)
    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    time.sleep(2)
    gc.collect()
    time.sleep(2)

    print(f"GPU allocated memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
    print(f"GPU reserved memory: {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

clear_memory()

GPU allocated memory: 0.00 GB
GPU reserved memory: 0.00 GB

# Model finetuning: Stage 1

Since the audio adapters are not trained yet, it makes sense to first freeze the language model and speech encoder and then train only the adapters.

In [7]:
processor = AutoProcessor.from_pretrained(
    "mdmy/whisper_asr_finetuning",
    subfolder="qwen_w_audio_processor",
    trust_remote_code=True
)

In [8]:
BASE_ID = "Qwen/Qwen2-VL-7B-Instruct"
cfg = Qwen2VLConfig.from_pretrained(BASE_ID, trust_remote_code=True)
cfg.use_audio = True
audio_cfg = Qwen2VLAudioConfig()
cfg.audio_config = audio_cfg

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

In [9]:
model = Qwen2VLForConditionalGenerationWithAudio.from_pretrained(
    "mdmy/whisper_asr_finetuning",
    config = cfg,
    subfolder="qwen2vl_with_audio_asr",
    trust_remote_code=True
)

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Downloading shards: 100%|██████████| 8/8 [00:00<00:00, 13.12it/s]
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 8/8 [00:01<00:00,  7.83it/s]

In [10]:
# freeze all parameters
for param in model.parameters():
    param.requires_grad = False

In [11]:
allow_patterns = [
        r"^audio_module\.audio_projection(\.|$)",  
        r"\.adapter(\.|$)",                        
        r"\.adapters(\.|$)",
        r"\blora(_|\.|$)",                         
        r"\.lora_[AB](\.|$)",
    ]

In [12]:
allow_res = [re.compile(pattern) for pattern in allow_patterns]

In [13]:
allow_res

[re.compile(r'^audio_module\.audio_projection(\.|$)', re.UNICODE),
 re.compile(r'\.adapter(\.|$)', re.UNICODE),
 re.compile(r'\.adapters(\.|$)', re.UNICODE),
 re.compile(r'\blora(_|\.|$)', re.UNICODE),
 re.compile(r'\.lora_[AB](\.|$)', re.UNICODE)]

In [14]:
def is_allowed(name: str) -> bool:
    return any(r.search(name) for r in allow_res)

In [15]:
trainable = []
for name, param in model.named_parameters():
    if is_allowed(name):
        print(name)
        param.requires_grad = True
        trainable.append(name)

audio_module.audio_projection.weight

In [16]:
tot = sum(p.numel() for p in model.parameters())
trn = sum(p.numel() for p in model.parameters() if p.requires_grad)

In [17]:
print(f"Trainable params: {trn:,} / {tot:,} ({100.0*trn/max(tot,1):.4f}%)")

Trainable params: 4,587,520 / 8,932,932,096 (0.0514%)

In [19]:
# Define the SFTConfig
training_args = SFTConfig(
    output_dir="sft_output",
    num_train_epochs=1,
    gradient_checkpointing=True,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,

    optim="adamw_torch_fused",
    learning_rate=1e-4,
    lr_scheduler_type="cosine",
    warmup_ratio = 0.03,
    max_grad_norm=0.5,
    
    eval_strategy="steps",
    save_strategy="steps",
    logging_steps=10,
    eval_steps=50,
    save_steps=500,
    metric_for_best_model='eval_loss',
    greater_is_better=False,
    load_best_model_at_end=True,

    bf16=True,
    tf32=True,

    push_to_hub=True,
    report_to="wandb",

    label_names = ["labels"],
    dataset_kwargs = {"skip_prepare_dataset": True},
    remove_unused_columns=False,
)

In [20]:
wandb.init(project='qwen-asr-finetuning',
           name='audio_projection_sft',
           config=training_args)

In [9]:
# create a data collator to encoder text and audio pairs
def collator(samples):
    processed = []
    for sample in samples:
        formatted = format_data(sample)
        text = processor.apply_chat_template(formatted, tokenize=False)

        audio_bytes = sample["wav"]["bytes"]
        audio_np, sr = fetch_audio(audio_bytes)  # returns 1D numpy/torch

        batch = processor(
            text=text,
            audios=audio_np,
            audio_sample_rate=sr,
            return_tensors="pt",
        )

        audio_token_ids = [audio_cfg.start_token_id, audio_cfg.token_id, audio_cfg.end_token_id]
        labels = batch.input_ids.clone()
        for tok in audio_token_ids:
            labels[batch.input_ids == tok] = -100

        attention_mask = torch.ones_like(batch.input_ids)

        # Ensure raw waveform tensor (B,T) for the model; use the same waveform you passed to processor
        audio_tensor = torch.as_tensor(audio_np)  # (T,)
        if audio_tensor.dim() == 1:
            audio_tensor = audio_tensor.unsqueeze(0)  # (1,T)

        processed.append({
            "input_ids": batch.input_ids.squeeze(0),
            "labels": labels.squeeze(0),
            "attention_mask": attention_mask.squeeze(0),
            "audio_values": audio_tensor.squeeze(0),  # will stack to (B,T) below
        })

    return {
        "input_ids": torch.stack([s["input_ids"] for s in processed]),
        "labels": torch.stack([s["labels"] for s in processed]),
        "attention_mask": torch.stack([s["attention_mask"] for s in processed]),
        "audio_values": torch.stack([s["audio_values"] for s in processed]),  # (B,T)
    }

In [22]:
trainer = SFTTrainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = test_dataset,
    data_collator = collator,
    processing_class = processor.tokenizer,
    
)

In [23]:
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...

Could not locate the best model at sft_output/checkpoint-3550/pytorch_model.bin, if you are running a distributed training on multiple nodes, you should activate `--save_on_each_node`.

TrainOutput(global_step=3727, training_loss=2.010938155161717, metrics={'train_runtime': 7390.5149, 'train_samples_per_second': 4.035, 'train_steps_per_second': 0.504, 'total_flos': 1.0591489294236979e+18, 'train_loss': 2.010938155161717})

In [24]:
trainer.save_model(training_args.output_dir)

wandb: WARNING The get_url method is deprecated and will be removed in a future release. Please use `run.url` instead.
Processing Files (10 / 10): 100%|██████████| 35.7GB / 35.7GB, 2.08GB/s
New Data Upload: |          |  0.00B /  0.00B,  0.00B/s

In [25]:
# clear GPU memory after training
import gc
import time

def clear_memory():
    # Delete variables if they exist in the current global scope
    if 'inputs' in globals(): del globals()['inputs']
    if 'model' in globals(): del globals()['model']
    if 'processor' in globals(): del globals()['processor']
    if 'trainer' in globals(): del globals()['trainer']
    if 'peft_model' in globals(): del globals()['peft_model']
    if 'bnb_config' in globals(): del globals()['bnb_config']
    time.sleep(2)

    # Garbage collection and clearing CUDA memory
    gc.collect()
    time.sleep(2)
    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    time.sleep(2)
    gc.collect()
    time.sleep(2)

    print(f"GPU allocated memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
    print(f"GPU reserved memory: {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

clear_memory()

GPU allocated memory: 2.09 GB
GPU reserved memory: 2.19 GB

In [26]:
audio_model = Qwen2VLForConditionalGenerationWithAudio.from_pretrained(training_args.output_dir)

Loading checkpoint shards: 100%|██████████| 8/8 [00:03<00:00,  2.08it/s]

In [27]:
audio_model.push_to_hub("mdmy/qwen2-vl-audio-projection-sft")

Processing Files (8 / 8): 100%|██████████| 35.7GB / 35.7GB, 2.03GB/s
New Data Upload: |          |  0.00B /  0.00B,  0.00B/s

CommitInfo(commit_url='https://huggingface.co/mdmy/qwen2-vl-audio-projection-sft/commit/38c3df6984ad0aef017d1ac0765b968df5b29f05', commit_message='Upload Qwen2VLForConditionalGenerationWithAudio', commit_description='', oid='38c3df6984ad0aef017d1ac0765b968df5b29f05', pr_url=None, repo_url=RepoUrl('https://huggingface.co/mdmy/qwen2-vl-audio-projection-sft', endpoint='https://huggingface.co', repo_type='model', repo_id='mdmy/qwen2-vl-audio-projection-sft'), pr_revision=None, pr_num=None)

## Model finetuning: Stage 2

Now that we have trained the audio projection/adapter, we can finetune the entire model e2e with QLoRA.

QLoRA enables efficient fine-tuning of large language models while significantly reducing the memory footprint compared to traditional methods. Unlike standard LoRA, which reduces memory usage by applying a low-rank approximation, QLoRA takes it a step further by quantizing the model weights. This leads to even lower memory requirements and improved training efficiency, making it an excellent choice for optimizing our model's performance without sacrificing quality.

In [10]:
from peft import LoraConfig, get_peft_model
from transformers import BitsAndBytesConfig
from trl import SFTTrainer
# Task: create LoRA, BitsAndBytes, and SFT configs and apply LoRA to the model

In [11]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16 # do the computations in bfloat16
)

In [12]:
BASE_ID = "Qwen/Qwen2-VL-7B-Instruct"
cfg = Qwen2VLConfig.from_pretrained(BASE_ID, trust_remote_code=True)
cfg.use_audio = True
audio_cfg = Qwen2VLAudioConfig()
cfg.audio_config = audio_cfg

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

In [13]:
model = Qwen2VLForConditionalGenerationWithAudio.from_pretrained(
    "mdmy/qwen2-vl-audio-projection-sft",
    config = cfg,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    quantization_config=bnb_config,
)

Downloading shards: 100%|██████████| 8/8 [00:00<00:00, 13.91it/s]
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 8/8 [00:05<00:00,  1.41it/s]

In [14]:
import bitsandbytes as bnb
import torch.nn as nn
BNB_LINEARS = (bnb.nn.Linear4bit, bnb.nn.Linear8bitLt)

suffixes = set()
for name, module in model.named_modules():
    if isinstance(module, (nn.Linear, *BNB_LINEARS)):
            suffixes.add(name.split(".")[-1])

In [15]:
sorted(suffixes)

['0',
 '2',
 'audio_projection',
 'down_proj',
 'fc1',
 'fc2',
 'gate_proj',
 'k_proj',
 'lm_head',
 'o_proj',
 'out_proj',
 'proj',
 'q_proj',
 'qkv',
 'up_proj',
 'v_proj']

In [16]:
desired_targets = {
    "q_proj", "k_proj", "v_proj", "o_proj", "qkv", "out_proj",
    "gate_proj", "up_proj", "down_proj", "audio_projection",
}
target_modules = sorted(list(desired_targets))

In [17]:
peft_config = LoraConfig(
    r=8,
    lora_alpha=16,           # rule of thumb: alpha ≈ 2*r
    lora_dropout=0.05,
    bias="none",
    target_modules=target_modules,
    task_type="CAUSAL_LM",
)

In [18]:
# Define the SFTConfig
training_args = SFTConfig(
    output_dir="e2e_sft_post_audio_projection_sft",
    num_train_epochs=1,
    gradient_checkpointing=True,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,

    optim="adamw_torch_fused",
    learning_rate=1e-4,
    lr_scheduler_type="cosine",
    warmup_ratio = 0.03,
    max_grad_norm=0.5,
    
    eval_strategy="steps",
    save_strategy="steps",
    logging_steps=10,
    eval_steps=50,
    save_steps=500,
    metric_for_best_model='eval_loss',
    greater_is_better=False,
    load_best_model_at_end=True,

    bf16=True,
    tf32=True,

    push_to_hub=True,
    report_to="wandb",

    label_names = ["labels"],
    dataset_kwargs = {"skip_prepare_dataset": True},
    remove_unused_columns=False,
)

In [19]:
trainer = SFTTrainer(
    model = model,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = test_dataset,
    data_collator = collator,
    processing_class = processor.tokenizer,
    peft_config = peft_config,
    
)

In [20]:
wandb.init(project='qwen-asr-finetuning',
           name='e2e_sft',
           config=training_args)

In [21]:
trainer.train()

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]

/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:92: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/home/ubuntu/audio/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py:295: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with torch.enable_grad(), device_autocast_ctx, torch.cpu.amp.autocast(**ctx.cpu_autocast_kwargs):  # type: ignore[attr-defined]
Could not locate the best model at e2e_sft_post_audio_projection_sft/checkpoint-3600/pytorch_model.bin, if you are running a distributed training on multiple nodes, you should activate `--save_on_each_node`.

TrainOutput(global_step=3727, training_loss=0.09003834197308187, metrics={'train_runtime': 14303.8265, 'train_samples_per_second': 2.085, 'train_steps_per_second': 0.261, 'total_flos': 1.0621998388076237e+18, 'train_loss': 0.09003834197308187})

In [22]:
trainer.save_model(training_args.output_dir)

wandb: WARNING The get_url method is deprecated and will be removed in a future release. Please use `run.url` instead.
Processing Files (3 / 3): 100%|██████████|  108MB /  108MB, 11.5MB/s
New Data Upload: |          |  0.00B /  0.00B,  0.00B/s

In [23]:
# clear GPU memory after training
import gc
import time

def clear_memory():
    # Delete variables if they exist in the current global scope
    if 'inputs' in globals(): del globals()['inputs']
    if 'model' in globals(): del globals()['model']
    if 'processor' in globals(): del globals()['processor']
    if 'trainer' in globals(): del globals()['trainer']
    if 'peft_model' in globals(): del globals()['peft_model']
    if 'bnb_config' in globals(): del globals()['bnb_config']
    time.sleep(2)

    # Garbage collection and clearing CUDA memory
    gc.collect()
    time.sleep(2)
    torch.cuda.empty_cache()
    torch.cuda.synchronize()
    time.sleep(2)
    gc.collect()
    time.sleep(2)

    print(f"GPU allocated memory: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
    print(f"GPU reserved memory: {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

clear_memory()

GPU allocated memory: 1.08 GB
GPU reserved memory: 1.18 GB

In [24]:
e2e_model = Qwen2VLForConditionalGenerationWithAudio.from_pretrained(training_args.output_dir)

Loading checkpoint shards: 100%|██████████| 8/8 [00:01<00:00,  5.54it/s]

In [25]:
e2e_model.push_to_hub("mdmy/audio-capable-qwen2-vl")

Processing Files (1 / 1): 100%|██████████| 96.7MB / 96.7MB,  0.00B/s
New Data Upload: |          |  0.00B /  0.00B,  0.00B/s

CommitInfo(commit_url='https://huggingface.co/mdmy/audio-capable-qwen2-vl/commit/09bd72a90d483391ec58a5f26fbd2be1b9b13058', commit_message='Upload Qwen2VLForConditionalGenerationWithAudio', commit_description='', oid='09bd72a90d483391ec58a5f26fbd2be1b9b13058', pr_url=None, repo_url=RepoUrl('https://huggingface.co/mdmy/audio-capable-qwen2-vl', endpoint='https://huggingface.co', repo_type='model', repo_id='mdmy/audio-capable-qwen2-vl'), pr_revision=None, pr_num=None)

# 5. Testing the Fine-Tuned Model 🔍

Now that we've successfully fine-tuned our Audio-Language model, it's time to evaluate its performance! In this section, test the model using your own speech examples.

Recording and Preparing the Audio File
- Record an audio file: Use Voice Memos on Mac to record a speech example.
- Convert to WAV: Use  to convert the file to .wav.
- Resample the audio: Use torchaudio.transforms.Resample to resample the audio to 16K Hz, matching the model's training sampling rate.

Finally save it to an in-memory BytesIO object and include it in tour conversation template and feed to the model for transcription.

In [26]:
clear_memory()

NameError: name 'clear_memory' is not defined

In [4]:
import io
import torchaudio
import torchaudio.transforms as T
from transformers import AutoProcessor, AutoModelForCausalLM
from qwen_vl_utils import fetch_audio

In [5]:
audio_path = "reading_test.wav"
waveform, sample_rate = torchaudio.load(audio_path)

In [6]:
sample_rate

48000

In [7]:
sample_rate = 16000

# Convert to bytes
audio_bytes_io = io.BytesIO()
torchaudio.save(audio_bytes_io, waveform, sample_rate, format='wav')
audio_bytes = audio_bytes_io.getvalue()

In [8]:
conversation = [
    {
        "content": [{
            "text": "You are an ASR model that transcribes speech to text. Avoid additional explanation unless absolutely necessary.",
            "type": "text"
        }],
        "role": "system"
    },
    {
        "content": [{
            "audio": audio_bytes,
            "type": "audio"
        },
        {
            "text": "Transcribe this speech into text.",
            "type": "text",
        }],
        "role": "user"
    }
]

In [9]:
processor = AutoProcessor.from_pretrained(
    "mdmy/whisper_asr_finetuning",
    subfolder="qwen_w_audio_processor",
    trust_remote_code=True
)

In [10]:
BASE_ID = "Qwen/Qwen2-VL-7B-Instruct"
cfg = Qwen2VLConfig.from_pretrained(BASE_ID, trust_remote_code=True)
cfg.use_audio = True
audio_cfg = Qwen2VLAudioConfig()
cfg.audio_config = audio_cfg

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.

In [ ]:
# model = Qwen2VLForConditionalGenerationWithAudio.from_pretrained(
#     "mdmy/audio-capable-qwen2-vl",
#     config=cfg,
#     torch_dtype=torch.float32,
#     low_cpu_mem_usage=True,
#     ignore_mismatched_sizes=True,   # audio heads are new
#     trust_remote_code=True,
#     device_map='auto',                # single device for the test
# ).to("cuda")
# model.eval()

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Downloading shards: 100%|██████████| 8/8 [00:01<00:00,  6.28it/s]
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████| 8/8 [00:06<00:00,  1.23it/s]

Qwen2VLForConditionalGenerationWithAudio(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionSdpaAttention(
          (qkv): lora.Linear(
            (base_layer): Linear(in_features=1280, out_features=3840, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=1280, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=3840, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Sequential(
        (0): Linear(in_features=5120, out_features=5120, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=5120, out_features=3584, bias=True)
      )
    )
  )
  (audio_module): WhisperAudioEncoder(
    (whisper_encoder): WhisperEncoder(
      (conv1): Conv1d(128, 1280, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv2): Conv1d(1280, 1280, kernel_size=(3,), stride=(2,), padding=(1,))
      (embed_positions): Embedding(1500, 1280)
      (layers): ModuleList(
        (0-31): 32 x WhisperEncoderLayer(
          (self_attn): WhisperSdpaAttention(
            (k_proj): lora.Linear(
              (base_layer): Linear(in_features=1280, out_features=1280, bias=False)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=1280, out_features=8, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=8, out_features=1280, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
            (v_proj): lora.Linear(
              (base_layer): Linear(in_features=1280, out_features=1280, bias=True)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=1280, out_features=8, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=8, out_features=1280, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
            (q_proj): lora.Linear(
              (base_layer): Linear(in_features=1280, out_features=1280, bias=True)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=1280, out_features=8, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=8, out_features=1280, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
            (out_proj): lora.Linear(
              (base_layer): Linear(in_features=1280, out_features=1280, bias=True)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=1280, out_features=8, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=8, out_features=1280, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
          )
          (self_attn_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
          (final_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
    )
    (audio_projection): lora.Linear(
      (base_layer): Linear(in_features=1280, out_features=3584, bias=False)
      (lora_dropout): ModuleDict(
        (default): Dropout(p=0.05, inplace=False)
      )
      (lora_A): ModuleDict(
        (default): Linear(in_features=1280, out_features=8, bias=False)
      )
      (lora_B): ModuleDict(
        (default): Linear(in_features=8, out_features=3584, bias=False)
      )
      (lora_embedding_A): ParameterDict()
      (lora_embedding_B): ParameterDict()
      (lora_magnitude_vector): ModuleDict()
    )
  )
  (model): Qwen2VLModel(
    (embed_tokens): Embedding(152064, 3584)
    (layers): ModuleList(
      (0-27): 28 x Qwen2VLDecoderLayer(
        (self_attn): Qwen2VLSdpaAttention(
          (q_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=3584, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=3584, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (k_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=512, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=512, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (v_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=512, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=512, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (o_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=3584, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=3584, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (rotary_emb): Qwen2VLRotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=18944, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=18944, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (up_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=18944, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=18944, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (down_proj): lora.Linear(
            (base_layer): Linear(in_features=18944, out_features=3584, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=18944, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=3584, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((3584,), eps=1e-06)
    (rotary_emb): Qwen2VLRotaryEmbedding()
  )
  (lm_head): Linear(in_features=3584, out_features=152064, bias=False)
)

In [19]:
model = Qwen2VLForConditionalGenerationWithAudio.from_pretrained(
    "e2e_sft_post_audio_projection_sft/checkpoint-2000",
    config=cfg,
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
    ignore_mismatched_sizes=True,
    trust_remote_code=True,
    device_map='auto',
).to("cuda")
model.eval()

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Downloading shards: 100%|██████████| 8/8 [00:00<00:00, 16.53it/s]
Loading checkpoint shards: 100%|██████████| 8/8 [00:07<00:00,  1.14it/s]

Qwen2VLForConditionalGenerationWithAudio(
  (visual): Qwen2VisionTransformerPretrainedModel(
    (patch_embed): PatchEmbed(
      (proj): Conv3d(3, 1280, kernel_size=(2, 14, 14), stride=(2, 14, 14), bias=False)
    )
    (rotary_pos_emb): VisionRotaryEmbedding()
    (blocks): ModuleList(
      (0-31): 32 x Qwen2VLVisionBlock(
        (norm1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (norm2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (attn): VisionSdpaAttention(
          (qkv): lora.Linear(
            (base_layer): Linear(in_features=1280, out_features=3840, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=1280, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=3840, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (proj): Linear(in_features=1280, out_features=1280, bias=True)
        )
        (mlp): VisionMlp(
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (act): QuickGELUActivation()
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
        )
      )
    )
    (merger): PatchMerger(
      (ln_q): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
      (mlp): Sequential(
        (0): Linear(in_features=5120, out_features=5120, bias=True)
        (1): GELU(approximate='none')
        (2): Linear(in_features=5120, out_features=3584, bias=True)
      )
    )
  )
  (audio_module): WhisperAudioEncoder(
    (whisper_encoder): WhisperEncoder(
      (conv1): Conv1d(128, 1280, kernel_size=(3,), stride=(1,), padding=(1,))
      (conv2): Conv1d(1280, 1280, kernel_size=(3,), stride=(2,), padding=(1,))
      (embed_positions): Embedding(1500, 1280)
      (layers): ModuleList(
        (0-31): 32 x WhisperEncoderLayer(
          (self_attn): WhisperSdpaAttention(
            (k_proj): lora.Linear(
              (base_layer): Linear(in_features=1280, out_features=1280, bias=False)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=1280, out_features=8, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=8, out_features=1280, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
            (v_proj): lora.Linear(
              (base_layer): Linear(in_features=1280, out_features=1280, bias=True)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=1280, out_features=8, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=8, out_features=1280, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
            (q_proj): lora.Linear(
              (base_layer): Linear(in_features=1280, out_features=1280, bias=True)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=1280, out_features=8, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=8, out_features=1280, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
            (out_proj): lora.Linear(
              (base_layer): Linear(in_features=1280, out_features=1280, bias=True)
              (lora_dropout): ModuleDict(
                (default): Dropout(p=0.05, inplace=False)
              )
              (lora_A): ModuleDict(
                (default): Linear(in_features=1280, out_features=8, bias=False)
              )
              (lora_B): ModuleDict(
                (default): Linear(in_features=8, out_features=1280, bias=False)
              )
              (lora_embedding_A): ParameterDict()
              (lora_embedding_B): ParameterDict()
              (lora_magnitude_vector): ModuleDict()
            )
          )
          (self_attn_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1280, out_features=5120, bias=True)
          (fc2): Linear(in_features=5120, out_features=1280, bias=True)
          (final_layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
    )
    (audio_projection): lora.Linear(
      (base_layer): Linear(in_features=1280, out_features=3584, bias=False)
      (lora_dropout): ModuleDict(
        (default): Dropout(p=0.05, inplace=False)
      )
      (lora_A): ModuleDict(
        (default): Linear(in_features=1280, out_features=8, bias=False)
      )
      (lora_B): ModuleDict(
        (default): Linear(in_features=8, out_features=3584, bias=False)
      )
      (lora_embedding_A): ParameterDict()
      (lora_embedding_B): ParameterDict()
      (lora_magnitude_vector): ModuleDict()
    )
  )
  (model): Qwen2VLModel(
    (embed_tokens): Embedding(152064, 3584)
    (layers): ModuleList(
      (0-27): 28 x Qwen2VLDecoderLayer(
        (self_attn): Qwen2VLSdpaAttention(
          (q_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=3584, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=3584, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (k_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=512, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=512, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (v_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=512, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=512, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (o_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=3584, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=3584, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (rotary_emb): Qwen2VLRotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=18944, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=18944, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (up_proj): lora.Linear(
            (base_layer): Linear(in_features=3584, out_features=18944, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=3584, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=18944, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (down_proj): lora.Linear(
            (base_layer): Linear(in_features=18944, out_features=3584, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.05, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=18944, out_features=8, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=8, out_features=3584, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((3584,), eps=1e-06)
    (rotary_emb): Qwen2VLRotaryEmbedding()
  )
  (lm_head): Linear(in_features=3584, out_features=152064, bias=False)
)

In [20]:
# Apply chat template and process
text = processor.apply_chat_template(conversation, tokenize=False, add_generation_prompt=True)
audio_np, sr = fetch_audio(audio_bytes)

In [21]:
# Run inference
batch = processor(
    text=text,
    audios=audio_np,
    audio_sample_rate=sr,
    return_tensors="pt"
).to("cuda")

In [22]:
# Generate
model.eval()
with torch.inference_mode():
    gen_out = model.generate(
        input_ids=batch['input_ids'],
        attention_mask=batch['attention_mask'],
        audio_values=batch['audio_values'],  # consumed on step 0 by prepare_inputs_for_generation
        max_new_tokens=1024,  # Use the parameter
        do_sample=False,            # set True + temperature/top_p if you want sampling
        use_cache=True,
        return_dict_in_generate=True,
        
        # output_scores=False,        # flip on if you need token-level scores
    )
    generated_ids = gen_out.sequences

In [23]:
generated_ids_trimmed = [
        out_ids[len(in_ids):] for in_ids, out_ids in zip(batch["input_ids"], generated_ids)
    ]

In [24]:
text = processor.tokenizer.batch_decode(
        generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )[0]

In [25]:
text

"        I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA AND I THINK THAT'S A GOOD IDEA"

In [ ]:
speech_brain = load_dataset("speechbrain/LargeScaleASR", "small",streaming=True)

In [63]:
sample = next(iter(speech_brain['test'].take(1)))

In [64]:
formatted_conversation = format_data(sample)

In [65]:
text_with_template = processor.apply_chat_template(
    formatted_conversation, 
    tokenize=False, 
    add_generation_prompt=False
)

In [66]:
text_with_template

'<|im_start|>system\n        You are an ASR model that transcribes speech to text. Avoid additional explanation unless absolutely necessary.\n<|im_end|>\n<|im_start|>user\n        <|audio_start|><|audio_pad|><|audio_end|>\n        Transcribe this speech into text.\n<|im_end|>\n<|im_start|>assistant\n        WHILE WE CANNOT COMPROMISE ON OUR VALUES AND OUR POSITIONS WE CAN STILL WORK TOGETHER ON MANY ISSUES\n<|im_end|>\n'

In [52]:
import librosa

In [91]:
sample['wav']['path']

'20180911-0900-PLENARY-en_20180911-20:17:50_2.wav'

In [89]:
audio_bytes = sample['wav']
audio_data, sampling_rate = librosa.load(io.BytesIO(audio_bytes), sr=None)

TypeError: a bytes-like object is required, not 'dict'

In [68]:
batch = processor(text=text_with_template, 
                  audios=audio_data, 
                  audio_sample_rate=sampling_rate, 
                  return_tensors="pt")

In [69]:
batch.to("cuda")

{'input_ids': tensor([[151644,   8948,    198,    286,   1446,    525,    458,   5752,     49,
           1614,    429,   1356,  55136,   8806,    311,   1467,     13,  34006,
           5107,  16148,   7241,  10875,   5871,    624, 151645,    198, 151644,
            872,    198,    260, 151657, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658, 151658,
         151659,    198,    286,   4058,   3114,    419,   8806,   1119,   1467,
            624, 151645,    198, 151644,  77091,    198,    286,  92134,  19677,
            356,  46875,  21968,   3361,   9133,   6197,  44913,  14710,   3567,
          44913,  26494,  67761,  19677,  19508,  92250,  31804,   5146,   3806,
           3012,   6197,  98256,  36396,  11308,    198, 151645,    198]],
       device='cuda:0'), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0'), 'audio_values': tensor([-0.0032, -0.0033,  0.0020,  ..., -0.0024,  0.0000,  0.0036],
       device='cuda:0'), 'number_encoder_tokens': tensor([392], device='cuda:0', dtype=torch.int32), 'audio_length': 7.839}

In [70]:
# Generate
model.eval()
with torch.inference_mode():
    gen_out = model.generate(
        input_ids=batch['input_ids'],
        attention_mask=batch['attention_mask'],
        audio_values=batch['audio_values'],  # consumed on step 0 by prepare_inputs_for_generation
        max_new_tokens=1024,  # Use the parameter
        do_sample=False,            # set True + temperature/top_p if you want sampling
        use_cache=True,
        return_dict_in_generate=True,
        
        # output_scores=False,        # flip on if you need token-level scores
    )
    generated_ids = gen_out.sequences

/lambda/nfs/audio/transformers/src/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.01` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/lambda/nfs/audio/transformers/src/transformers/generation/configuration_utils.py:633: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.001` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/lambda/nfs/audio/transformers/src/transformers/generation/configuration_utils.py:650: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `1` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

In [71]:
generated_ids_trimmed = [
        out_ids[len(in_ids):] for in_ids, out_ids in zip(batch["input_ids"], generated_ids)
    ]

In [72]:
text = processor.tokenizer.batch_decode(
        generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )[0]

In [73]:
text

'assistant\n        WHILE WE CANNOT COMPROMISE ON OUR VALUES AND OUR POSITIONS WE CAN STILL WORK TOGETHER ON MANY ISSUES\n'

In [75]:
sample['text']

'WHILE WE CANNOT COMPROMISE ON OUR VALUES AND OUR POSITIONS WE CAN STILL WORK TOGETHER ON MANY ISSUES'